sonar.projectKey=kubernetes-web
sonar.projectName=kubernetes-web
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://host.docker.internal:9000
sonar.login=sqp_05b221e2b36d0a00b5f9f91c7339a8e865913917