sonar.projectKey=docker-web
sonar.projectName=docker-web
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://host.docker.internal:9000
sonar.login=sqp_0443db0dadf784217087afd8da0dbf13583d5a43